export function render() {
  return `
<div class="container mt-4">
  <div class="page-header">
    <h1>Port Reference</h1>
    <p>Search well-known TCP/UDP port numbers and their associated services.</p>
  </div>

  <div class="card shadow-sm mb-4">
    <div class="card-body">
      <input class="form-control" id="portSearch" placeholder="Search by port number, name, or protocol..." autofocus>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr><th>Port</th><th>Protocol</th><th>Service</th><th>Description</th></tr>
      </thead>
      <tbody id="portTableBody"></tbody>
    </table>
  </div>
  <p class="text-muted mt-2" id="portCount" style="font-size:0.85rem;"></p>
</div>`;
}

export function init() {
  const search = document.getElementById('portSearch');
  const tbody = document.getElementById('portTableBody');
  const countEl = document.getElementById('portCount');

  function renderTable(filter) {
    const q = (filter || '').toLowerCase();
    const filtered = q
      ? PORTS.filter(p =>
        String(p[0]).includes(q) ||
        p[1].toLowerCase().includes(q) ||
        p[2].toLowerCase().includes(q) ||
        p[3].toLowerCase().includes(q))
      : PORTS;

    tbody.innerHTML = filtered.map(p =>
      `<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td class="text-muted" style="font-size:0.85rem;">${p[3]}</td></tr>`
    ).join('');
    countEl.textContent = `${filtered.length} of ${PORTS.length} entries`;
  }

  search.addEventListener('input', () => renderTable(search.value));
  renderTable('');
}

// [port, protocol, service, description]
const PORTS = [
  // System / Well-Known Ports (0-1023)
  [1, 'TCP', 'TCPMUX', 'TCP Port Service Multiplexer'],
  [5, 'TCP', 'RJE', 'Remote Job Entry'],
  [7, 'TCP/UDP', 'Echo', 'Echo service'],
  [9, 'TCP/UDP', 'Discard', 'Discard / Wake-on-LAN'],
  [11, 'TCP', 'Systat', 'Active users'],
  [13, 'TCP', 'Daytime', 'Daytime protocol'],
  [17, 'TCP', 'QOTD', 'Quote of the Day'],
  [19, 'TCP/UDP', 'Chargen', 'Character Generator'],
  [20, 'TCP', 'FTP Data', 'File Transfer Protocol data channel'],
  [21, 'TCP', 'FTP Control', 'File Transfer Protocol command channel'],
  [22, 'TCP', 'SSH', 'Secure Shell remote access'],
  [23, 'TCP', 'Telnet', 'Unencrypted remote terminal access'],
  [25, 'TCP', 'SMTP', 'Simple Mail Transfer Protocol'],
  [37, 'TCP/UDP', 'Time', 'Time protocol'],
  [42, 'TCP/UDP', 'WINS', 'Windows Internet Name Service'],
  [43, 'TCP', 'WHOIS', 'WHOIS directory service'],
  [49, 'TCP/UDP', 'TACACS+', 'Terminal Access Controller Access-Control System'],
  [53, 'TCP/UDP', 'DNS', 'Domain Name System'],
  [67, 'UDP', 'DHCP Server', 'Dynamic Host Configuration Protocol server'],
  [68, 'UDP', 'DHCP Client', 'Dynamic Host Configuration Protocol client'],
  [69, 'UDP', 'TFTP', 'Trivial File Transfer Protocol'],
  [70, 'TCP', 'Gopher', 'Gopher protocol'],
  [79, 'TCP', 'Finger', 'Finger user information protocol'],
  [80, 'TCP', 'HTTP', 'Hypertext Transfer Protocol'],
  [88, 'TCP/UDP', 'Kerberos', 'Network authentication protocol'],
  [102, 'TCP', 'ISO-TSAP', 'ISO Transport Service Access Point'],
  [104, 'TCP', 'DICOM', 'Digital Imaging and Communications in Medicine'],
  [110, 'TCP', 'POP3', 'Post Office Protocol v3'],
  [111, 'TCP/UDP', 'RPCbind', 'ONC RPC portmapper'],
  [113, 'TCP', 'Ident', 'Authentication / identification protocol'],
  [119, 'TCP', 'NNTP', 'Network News Transfer Protocol'],
  [123, 'UDP', 'NTP', 'Network Time Protocol'],
  [135, 'TCP', 'MS RPC', 'Microsoft Remote Procedure Call'],
  [137, 'UDP', 'NetBIOS-NS', 'NetBIOS Name Service'],
  [138, 'UDP', 'NetBIOS-DGM', 'NetBIOS Datagram Service'],
  [139, 'TCP', 'NetBIOS-SSN', 'NetBIOS Session Service'],
  [143, 'TCP', 'IMAP', 'Internet Message Access Protocol'],
  [161, 'UDP', 'SNMP', 'Simple Network Management Protocol'],
  [162, 'UDP', 'SNMP Trap', 'SNMP notifications/traps'],
  [170, 'TCP', 'Print-SRV', 'Network PostScript print server'],
  [175, 'TCP', 'VMNET', 'VMNET virtual machine networking'],
  [179, 'TCP', 'BGP', 'Border Gateway Protocol'],
  [194, 'TCP', 'IRC', 'Internet Relay Chat'],
  [201, 'TCP', 'AppleTalk', 'AppleTalk routing maintenance'],
  [209, 'TCP', 'QMTP', 'Quick Mail Transfer Protocol'],
  [213, 'TCP/UDP', 'IPX', 'Internetwork Packet Exchange'],
  [220, 'TCP', 'IMAP3', 'Interactive Mail Access Protocol v3'],
  [259, 'TCP', 'ESRO', 'Efficient Short Remote Operations'],
  [264, 'TCP', 'BGMP', 'Border Gateway Multicast Protocol'],
  [311, 'TCP', 'macOS Server', 'Apple macOS Server Admin'],
  [318, 'TCP', 'TSP', 'Time Stamp Protocol'],
  [323, 'TCP/UDP', 'IMMP', 'Internet Message Mapping Protocol'],
  [383, 'TCP', 'HP Alerts', 'HP data alarm manager'],
  [389, 'TCP/UDP', 'LDAP', 'Lightweight Directory Access Protocol'],
  [411, 'TCP', 'Direct Connect', 'Direct Connect Hub'],
  [412, 'TCP', 'Direct Connect', 'Direct Connect Client-to-Client'],
  [427, 'TCP/UDP', 'SLP', 'Service Location Protocol'],
  [443, 'TCP', 'HTTPS', 'HTTP over TLS/SSL'],
  [445, 'TCP', 'SMB', 'Server Message Block / CIFS'],
  [464, 'TCP/UDP', 'Kpasswd', 'Kerberos password change'],
  [465, 'TCP', 'SMTPS', 'SMTP over SSL (deprecated)'],
  [497, 'TCP', 'Retrospect', 'Retrospect backup'],
  [500, 'UDP', 'IKE', 'Internet Key Exchange (IPsec)'],
  [502, 'TCP', 'Modbus', 'Modbus industrial protocol'],
  [512, 'TCP', 'rexec', 'Remote process execution'],
  [513, 'TCP', 'rlogin', 'Remote login'],
  [514, 'UDP', 'Syslog', 'System logging protocol'],
  [514, 'TCP', 'RSH', 'Remote shell'],
  [515, 'TCP', 'LPD', 'Line Printer Daemon'],
  [520, 'UDP', 'RIP', 'Routing Information Protocol'],
  [521, 'UDP', 'RIPng', 'RIP next generation (IPv6)'],
  [523, 'TCP', 'IBM DB2', 'IBM DB2 database'],
  [530, 'TCP', 'RPC', 'Remote Procedure Call'],
  [540, 'TCP', 'UUCP', 'Unix-to-Unix Copy Protocol'],
  [543, 'TCP', 'Klogin', 'Kerberos login'],
  [544, 'TCP', 'Kshell', 'Kerberos remote shell'],
  [546, 'TCP/UDP', 'DHCPv6 Client', 'DHCPv6 client'],
  [547, 'TCP/UDP', 'DHCPv6 Server', 'DHCPv6 server'],
  [548, 'TCP', 'AFP', 'Apple Filing Protocol'],
  [554, 'TCP/UDP', 'RTSP', 'Real Time Streaming Protocol'],
  [587, 'TCP', 'SMTP Submission', 'Mail submission (STARTTLS)'],
  [593, 'TCP', 'MS DCOM', 'Microsoft DCOM over HTTP'],
  [596, 'TCP', 'SMSD', 'SysMan Station Daemon'],
  [631, 'TCP/UDP', 'IPP', 'Internet Printing Protocol (CUPS)'],
  [636, 'TCP', 'LDAPS', 'LDAP over SSL'],
  [639, 'TCP', 'MSDP', 'Multicast Source Discovery Protocol'],
  [646, 'TCP', 'LDP', 'Label Distribution Protocol (MPLS)'],
  [691, 'TCP', 'MS Exchange', 'MS Exchange Routing'],
  [694, 'TCP', 'Linux-HA', 'Linux High-Availability heartbeat'],
  [749, 'TCP/UDP', 'Kerberos Admin', 'Kerberos v5 administration'],
  [853, 'TCP', 'DNS over TLS', 'Encrypted DNS queries (DoT)'],
  [873, 'TCP', 'rsync', 'Remote file synchronization'],
  [902, 'TCP', 'VMware', 'VMware ESXi console'],
  [993, 'TCP', 'IMAPS', 'IMAP over SSL'],
  [995, 'TCP', 'POP3S', 'POP3 over SSL'],

  // Registered Ports (1024-49151)
  [1080, 'TCP', 'SOCKS', 'SOCKS proxy protocol'],
  [1099, 'TCP', 'Java RMI', 'Java Remote Method Invocation'],
  [1194, 'UDP', 'OpenVPN', 'OpenVPN default port'],
  [1214, 'TCP', 'Kazaa', 'Kazaa P2P file sharing'],
  [1241, 'TCP', 'Nessus', 'Nessus vulnerability scanner'],
  [1293, 'TCP', 'IPsec', 'Internet Protocol Security'],
  [1311, 'TCP', 'Dell OME', 'Dell OpenManage HTTPS'],
  [1337, 'TCP', 'WASTE', 'WASTE encrypted file sharing'],
  [1433, 'TCP', 'MSSQL', 'Microsoft SQL Server'],
  [1434, 'UDP', 'MSSQL Browser', 'SQL Server Browser Service'],
  [1512, 'TCP/UDP', 'WINS', 'Windows Internet Name Service replication'],
  [1521, 'TCP', 'Oracle DB', 'Oracle Database listener'],
  [1527, 'TCP', 'Oracle', 'Oracle Database (alt)'],
  [1645, 'UDP', 'RADIUS (old)', 'RADIUS authentication (old port)'],
  [1646, 'UDP', 'RADIUS (old)', 'RADIUS accounting (old port)'],
  [1701, 'UDP', 'L2TP', 'Layer 2 Tunneling Protocol'],
  [1723, 'TCP', 'PPTP', 'Point-to-Point Tunneling Protocol'],
  [1741, 'TCP', 'CiscoWorks', 'CiscoWorks SNMS'],
  [1812, 'UDP', 'RADIUS Auth', 'RADIUS authentication'],
  [1813, 'UDP', 'RADIUS Acct', 'RADIUS accounting'],
  [1863, 'TCP', 'MSN', 'Microsoft Notification Protocol'],
  [1900, 'UDP', 'SSDP', 'Simple Service Discovery Protocol (UPnP)'],
  [1985, 'TCP/UDP', 'HSRP', 'Hot Standby Router Protocol (Cisco)'],
  [2049, 'TCP/UDP', 'NFS', 'Network File System'],
  [2053, 'TCP', 'Kerberos KDC', 'Kerberos key distribution center (alt)'],
  [2082, 'TCP', 'cPanel', 'cPanel HTTP'],
  [2083, 'TCP', 'cPanel SSL', 'cPanel HTTPS'],
  [2100, 'TCP', 'Oracle XDB', 'Oracle XML Database'],
  [2181, 'TCP', 'ZooKeeper', 'Apache ZooKeeper client'],
  [2222, 'TCP', 'SSH (alt)', 'SSH alternate port'],
  [2375, 'TCP', 'Docker', 'Docker REST API (unencrypted)'],
  [2376, 'TCP', 'Docker TLS', 'Docker REST API (encrypted)'],
  [2483, 'TCP', 'Oracle DB TLS', 'Oracle Database over TLS'],
  [2484, 'TCP', 'Oracle DB SSL', 'Oracle Database over SSL'],
  [2546, 'TCP/UDP', 'EVP', 'Elliptic Virtual Pointer'],
  [2593, 'TCP', 'RunUO', 'Ultima Online server'],
  [2598, 'TCP', 'Citrix', 'Citrix ICA session reliability'],
  [2638, 'TCP', 'SQL Anywhere', 'Sybase SQL Anywhere'],
  [2967, 'TCP', 'Symantec AV', 'Symantec AntiVirus'],
  [3000, 'TCP', 'Grafana', 'Grafana / dev servers'],
  [3074, 'TCP/UDP', 'Xbox Live', 'Xbox Live / gaming'],
  [3128, 'TCP', 'Squid', 'Squid HTTP proxy'],
  [3225, 'TCP/UDP', 'FCIP', 'Fibre Channel over IP'],
  [3260, 'TCP', 'iSCSI', 'Internet Small Computer System Interface'],
  [3268, 'TCP', 'AD GC', 'Active Directory Global Catalog'],
  [3269, 'TCP', 'AD GC SSL', 'Active Directory Global Catalog over SSL'],
  [3283, 'TCP', 'Apple ARD', 'Apple Remote Desktop'],
  [3306, 'TCP', 'MySQL', 'MySQL/MariaDB database'],
  [3389, 'TCP', 'RDP', 'Remote Desktop Protocol'],
  [3478, 'UDP', 'STUN/TURN', 'Session Traversal Utilities for NAT'],
  [3544, 'UDP', 'Teredo', 'Teredo IPv6 tunneling'],
  [3689, 'TCP', 'iTunes/DAAP', 'Digital Audio Access Protocol'],
  [3784, 'TCP/UDP', 'BFD', 'Bidirectional Forwarding Detection'],
  [3868, 'TCP', 'Diameter', 'Diameter signaling protocol'],
  [4000, 'TCP', 'Diablo II', 'Blizzard games / dev tools'],
  [4333, 'TCP', 'mSQL', 'Mini SQL'],
  [4443, 'TCP', 'Pharos', 'Pharos / alt HTTPS'],
  [4500, 'UDP', 'IPsec NAT-T', 'IPsec NAT Traversal'],
  [4662, 'TCP', 'eDonkey', 'eDonkey2000 P2P'],
  [4672, 'UDP', 'eMule', 'eMule P2P'],
  [4786, 'TCP', 'Cisco Smart Install', 'Cisco Smart Install'],
  [4789, 'UDP', 'VXLAN', 'Virtual Extensible LAN'],
  [4848, 'TCP', 'GlassFish', 'GlassFish admin console'],
  [5000, 'TCP', 'UPnP', 'Universal Plug and Play / Flask dev'],
  [5004, 'TCP/UDP', 'RTP', 'Real-time Transport Protocol'],
  [5005, 'TCP/UDP', 'RTCP', 'RTP Control Protocol'],
  [5050, 'TCP', 'Yahoo Msg', 'Yahoo! Messenger'],
  [5060, 'TCP/UDP', 'SIP', 'Session Initiation Protocol'],
  [5061, 'TCP', 'SIP TLS', 'SIP over TLS'],
  [5222, 'TCP', 'XMPP Client', 'XMPP / Jabber client connection'],
  [5269, 'TCP', 'XMPP Server', 'XMPP server-to-server'],
  [5353, 'UDP', 'mDNS', 'Multicast DNS (Bonjour)'],
  [5355, 'TCP/UDP', 'LLMNR', 'Link-Local Multicast Name Resolution'],
  [5432, 'TCP', 'PostgreSQL', 'PostgreSQL database'],
  [5500, 'TCP', 'VNC Server', 'VNC Server listener'],
  [5631, 'TCP', 'pcAnywhere', 'Symantec pcAnywhere data'],
  [5632, 'UDP', 'pcAnywhere', 'Symantec pcAnywhere status'],
  [5672, 'TCP', 'AMQP', 'Advanced Message Queuing Protocol (RabbitMQ)'],
  [5683, 'UDP', 'CoAP', 'Constrained Application Protocol (IoT)'],
  [5900, 'TCP', 'VNC', 'Virtual Network Computing'],
  [5938, 'TCP', 'TeamViewer', 'TeamViewer remote access'],
  [5984, 'TCP', 'CouchDB', 'CouchDB database'],
  [5985, 'TCP', 'WinRM HTTP', 'Windows Remote Management'],
  [5986, 'TCP', 'WinRM HTTPS', 'Windows Remote Management (SSL)'],
  [6379, 'TCP', 'Redis', 'Redis key-value store'],
  [6443, 'TCP', 'Kubernetes', 'Kubernetes API server'],
  [6514, 'TCP', 'Syslog TLS', 'Syslog over TLS'],
  [6660, 'TCP', 'IRC (alt)', 'IRC alternate range start'],
  [6667, 'TCP', 'IRC', 'IRC default port'],
  [6697, 'TCP', 'IRC TLS', 'IRC over TLS'],
  [6881, 'TCP/UDP', 'BitTorrent', 'BitTorrent default range start'],
  [7000, 'TCP', 'Cassandra', 'Apache Cassandra inter-node'],
  [7001, 'TCP', 'WebLogic', 'Oracle WebLogic Server'],
  [7070, 'TCP', 'RealServer', 'RealServer / RTSP alt'],
  [7199, 'TCP', 'Cassandra JMX', 'Apache Cassandra JMX monitoring'],
  [7443, 'TCP', 'Oracle AS', 'Oracle Application Server SSL'],
  [7547, 'TCP', 'CWMP', 'CPE WAN Management Protocol (TR-069)'],
  [7777, 'TCP', 'iChat', 'Apple iChat / game servers'],
  [8000, 'TCP', 'HTTP Alt', 'Alternative HTTP / dev servers'],
  [8008, 'TCP', 'HTTP Alt', 'Alternative HTTP'],
  [8080, 'TCP', 'HTTP Proxy', 'HTTP proxy / alternative HTTP'],
  [8081, 'TCP', 'HTTP Alt', 'HTTP alternative / admin'],
  [8088, 'TCP', 'Radan HTTP', 'Radan HTTP'],
  [8123, 'TCP', 'Home Assistant', 'Home Assistant / ClickHouse'],
  [8139, 'TCP', 'Puppet', 'Puppet agent'],
  [8140, 'TCP', 'Puppet Master', 'Puppet Server'],
  [8200, 'TCP', 'Vault', 'HashiCorp Vault'],
  [8291, 'TCP', 'MikroTik', 'MikroTik Winbox'],
  [8333, 'TCP', 'Bitcoin', 'Bitcoin peer-to-peer'],
  [8443, 'TCP', 'HTTPS Alt', 'Alternative HTTPS'],
  [8500, 'TCP', 'Consul', 'HashiCorp Consul HTTP API'],
  [8834, 'TCP', 'Nessus Web', 'Nessus web UI'],
  [8888, 'TCP', 'HTTP Alt', 'Alternative HTTP / Jupyter'],
  [9000, 'TCP', 'PHP-FPM', 'PHP FastCGI Process Manager / SonarQube'],
  [9001, 'TCP', 'Tor ORPort', 'Tor network relay'],
  [9042, 'TCP', 'Cassandra CQL', 'Apache Cassandra CQL native'],
  [9043, 'TCP', 'WebSphere', 'IBM WebSphere admin'],
  [9060, 'TCP', 'WebSphere', 'IBM WebSphere admin console'],
  [9090, 'TCP', 'Prometheus', 'Prometheus / web admin UIs'],
  [9092, 'TCP', 'Kafka', 'Apache Kafka broker'],
  [9100, 'TCP', 'JetDirect', 'HP JetDirect (network printing)'],
  [9200, 'TCP', 'Elasticsearch', 'Elasticsearch REST API'],
  [9300, 'TCP', 'ES Transport', 'Elasticsearch inter-node transport'],
  [9418, 'TCP', 'Git', 'Git protocol'],
  [9443, 'TCP', 'WSO2', 'WSO2 / alt HTTPS'],
  [9999, 'TCP', 'Urchin', 'Urchin / Dash / admin UIs'],
  [10000, 'TCP', 'Webmin', 'Webmin administration'],
  [10050, 'TCP', 'Zabbix Agent', 'Zabbix monitoring agent'],
  [10051, 'TCP', 'Zabbix Server', 'Zabbix monitoring server'],
  [10250, 'TCP', 'Kubelet', 'Kubernetes Kubelet API'],
  [10443, 'TCP', 'HTTPS Alt', 'Alternative HTTPS'],
  [11211, 'TCP/UDP', 'Memcached', 'Memcached caching system'],
  [11371, 'TCP', 'OpenPGP', 'OpenPGP HTTP Keyserver'],
  [13720, 'TCP', 'NetBackup', 'Veritas NetBackup'],
  [15672, 'TCP', 'RabbitMQ', 'RabbitMQ management UI'],
  [16080, 'TCP', 'Mac Sharing', 'macOS Web Sharing'],
  [17500, 'TCP', 'Dropbox', 'Dropbox LAN sync'],
  [18080, 'TCP', 'Monero RPC', 'Monero JSON-RPC'],
  [19132, 'UDP', 'Minecraft BE', 'Minecraft Bedrock Edition'],
  [20000, 'TCP', 'Usermin', 'Usermin administration'],
  [22222, 'TCP', 'SSH (alt)', 'SSH alternate port'],
  [25565, 'TCP', 'Minecraft', 'Minecraft Java Edition'],
  [25575, 'TCP', 'Minecraft RCON', 'Minecraft remote console'],
  [27015, 'UDP', 'Source Engine', 'Valve Source Engine (Steam)'],
  [27017, 'TCP', 'MongoDB', 'MongoDB database'],
  [27018, 'TCP', 'MongoDB Shard', 'MongoDB shard server'],
  [27019, 'TCP', 'MongoDB Config', 'MongoDB config server'],
  [28015, 'UDP', 'Rust', 'Rust game server'],
  [28017, 'TCP', 'MongoDB Web', 'MongoDB web status (legacy)'],
  [30000, 'TCP', 'Plex', 'Plex relay / misc services'],
  [32400, 'TCP', 'Plex Media', 'Plex Media Server'],
  [33434, 'UDP', 'Traceroute', 'Traceroute default start port'],
  [43594, 'TCP', 'RuneScape', 'RuneScape login server'],
  [47808, 'UDP', 'BACnet', 'Building Automation and Control'],

  // Dynamic / Private Range markers
  [49152, 'TCP/UDP', 'Ephemeral Start', 'Start of dynamic/ephemeral range (IANA)'],
  [65535, 'TCP/UDP', 'Max Port', 'Maximum valid port number'],
];
