const fs = require('fs');
const path = require('path');

// --- HELPERS ---
const rand = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const randItem = (arr) => arr[rand(0, arr.length - 1)];
const generateIP = () => `${rand(10, 223)}.${rand(0, 255)}.${rand(0, 255)}.${rand(1, 254)}`;
const generateMAC = () => Array.from({length: 6}, () => rand(0, 255).toString(16).padStart(2, '0')).join(':');
const intf = () => randItem(['GigabitEthernet', 'FastEthernet', 'TenGigabitEthernet']) + rand(0, 3) + '/' + rand(0, 24);

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// --- STATIC FLASHCARDS ---
const FLASHCARDS = {
    ccna: [
        { domain: "1.0", front: "What is the primary purpose of a Default Gateway?", back: "To route traffic to destinations outside of the local subnet." },
        { domain: "1.0", front: "What IPv6 address is equivalent to the IPv4 loopback?", back: "::1" },
        { domain: "2.0", front: "What is the multicast MAC address prefix used by STP BPDUs?", back: "01:80:C2:00:00:00" },
        { domain: "3.0", front: "What is the default Administrative Distance of an External EIGRP route?", back: "170" },
        { domain: "4.0", front: "What happens when a switch port configured with BPDU Guard receives a BPDU?", back: "The port is immediately placed into an err-disabled state." },
        { domain: "2.0", front: "Which command reveals the MAC address table on a Cisco switch?", back: "show mac address-table" },
        { domain: "4.0", front: "What is the well-known TCP port for BGP?", back: "TCP 179" },
        { domain: "2.0", front: "What is the default priority value for STP?", back: "32768" },
        { domain: "5.0", front: "What mechanism allows a single public IP to be shared by multiple internal hosts?", back: "Port Address Translation (PAT) / NAT Overload" }
    ],
    netplus: [
        { domain: "1.0", front: "Which OSI layer is responsible for routing?", back: "Layer 3 (Network Layer)" },
        { domain: "2.0", front: "What port does HTTP use?", back: "TCP Port 80" },
        { domain: "2.0", front: "What port does HTTPS use?", back: "TCP Port 443" },
        { domain: "1.0", front: "What is the purpose of DNS?", back: "Resolves hostnames to IP addresses." },
        { domain: "3.0", front: "What command is used to trace the path a packet takes on Windows?", back: "tracert" },
        { domain: "4.0", front: "What type of attack floods a switch's MAC table?", back: "MAC Flooding" },
        { domain: "5.0", front: "What does a TDR (Time-Domain Reflectometer) do?", back: "Locates faults in copper cables." },
        { domain: "1.0", front: "Which frequency band does 802.11a use?", back: "5 GHz" }
    ],
    secplus: [
        { domain: "1.0", front: "What is the principle of Least Privilege?", back: "Giving users only the permissions necessary to do their job." },
        { domain: "2.0", front: "What is a zero-day vulnerability?", back: "A vulnerability that is unknown to the vendor and has no patch." },
        { domain: "3.0", front: "What does IPsec ESP provide?", back: "Encryption and authentication for the payload." },
        { domain: "4.0", front: "What is the purpose of a SIEM?", back: "Centralized log aggregation and security event correlation." },
        { domain: "5.0", front: "What is MFA?", back: "Multi-Factor Authentication (requires two or more distinct types of authentication factors)." },
        { domain: "2.0", front: "What attack intercepts communication between two parties?", back: "On-path / Man-in-the-Middle (MitM) attack." }
    ],
    encor: [
        { domain: "1.0", front: "What is Cisco SD-WAN?", back: "A software-defined approach to managing wide-area networks." },
        { domain: "2.0", front: "What is a VRF?", back: "Virtual Routing and Forwarding, allows multiple instances of a routing table to co-exist." },
        { domain: "3.0", front: "What BGP attribute is used to influence inbound traffic from an external AS?", back: "MED (Multi-Exit Discriminator)" },
        { domain: "3.0", front: "Which OSPF LSA type is generated by an ASBR?", back: "Type 5 (External LSA)" },
        { domain: "4.0", front: "What is NetFlow?", back: "A network protocol developed by Cisco for collecting IP traffic information." },
        { domain: "5.0", front: "What data format does RESTCONF use?", back: "XML and JSON" }
    ],
    jncia: [
        { domain: "2.0", front: "What mode do you enter when you type 'configure' in Junos?", back: "Configuration Mode" },
        { domain: "3.0", front: "What is the default route preference for a Static Route in Junos?", back: "5" },
        { domain: "3.0", front: "What is the default route preference for OSPF internal routes in Junos?", back: "10" },
        { domain: "4.0", front: "What command commits a configuration but reverts it if not confirmed in 10 minutes?", back: "commit confirmed" },
        { domain: "5.0", front: "Which command shows the active routing table in Junos?", back: "show route" },
        { domain: "4.0", front: "In Junos firewall filters, what is the default action if no term matches?", back: "Discard (Implicit Deny)" }
    ]
};

// --- PROCEDURAL FLASHCARD GENERATORS ---
const procFlashcards = () => {
    const network = rand(10, 200);
    const cidr = rand(24, 29);
    const hostBits = 32 - cidr;
    const blockSize = Math.pow(2, hostBits);
    const netIdNum = rand(0, (256/blockSize)-1) * blockSize;
    const bcastNum = netIdNum + blockSize - 1;
    const ipNum = rand(netIdNum + 1, bcastNum - 1);
    const ip = `192.168.${network}.${ipNum}`;
    
    return [
        { domain: "1.0", front: `What is the Network ID for ${ip}/${cidr}?`, back: `192.168.${network}.${netIdNum}` },
        { domain: "1.0", front: `What is the Broadcast Address for ${ip}/${cidr}?`, back: `192.168.${network}.${bcastNum}` },
        { domain: "1.0", front: `How many usable hosts are available in a /${cidr} subnet?`, back: `${Math.pow(2, hostBits) - 2} usable hosts` }
    ];
};

// --- HARDENED PROCEDURAL QUESTION TEMPLATES ---

const TPL_SUBNETTING = () => {
    const network = rand(10, 200);
    const cidr = randItem([26, 27, 28, 29]);
    const hostBits = 32 - cidr;
    const blockSize = Math.pow(2, hostBits);
    
    // Pick a random subnet within the /24
    const netIdNum = rand(1, (256/blockSize)-2) * blockSize;
    const bcastNum = netIdNum + blockSize - 1;
    const ipNum = rand(netIdNum + 1, bcastNum - 1);
    
    // HARDENED DISTRACTORS: Adjacent subnet IDs and broadcasts
    const nextNetIdNum = netIdNum + blockSize;
    const prevBcastNum = netIdNum - 1;
    
    const ip = `192.168.${network}.${ipNum}`;
    const bcast = `192.168.${network}.${bcastNum}`;
    const netId = `192.168.${network}.${netIdNum}`;
    const nextNetId = `192.168.${network}.${nextNetIdNum}`;
    const prevBcast = `192.168.${network}.${prevBcastNum}`;
    
    return {
        domain: "1.0",
        type: "multiple-choice",
        text: `A host is configured with the IP address ${ip}/${cidr}. What is the broadcast address for this specific subnet?`,
        options: [bcast, netId, nextNetId, prevBcast],
        answer: [bcast],
        explanation: `For a /${cidr} subnet, the block size is ${blockSize}. The subnet ID for ${ip} is ${netId}. The broadcast address is the last IP before the next subnet (${nextNetId}), which makes it ${bcast}.`
    };
};

const TPL_PORTS = () => {
    // HARDENED: Distractors grouped by category (e.g. Secure protocols, Email protocols)
    const portCategories = [
        [ { p: 22, n: 'SSH' }, { p: 443, n: 'HTTPS' }, { p: 636, n: 'LDAPS' }, { p: 993, n: 'IMAPS' } ], // Secure
        [ { p: 25, n: 'SMTP' }, { p: 110, n: 'POP3' }, { p: 143, n: 'IMAP' }, { p: 587, n: 'SMTP (Submission)' } ], // Email
        [ { p: 67, n: 'DHCP' }, { p: 53, n: 'DNS' }, { p: 123, n: 'NTP' }, { p: 161, n: 'SNMP' } ] // Infrastructure
    ];
    const category = randItem(portCategories);
    const target = randItem(category);
    const wrong = category.filter(x => x.p !== target.p).sort(() => 0.5 - Math.random()).slice(0, 3);
    
    return {
        domain: "2.0",
        type: "multiple-choice",
        text: `Which well-known port is utilized by the ${target.n} protocol?`,
        options: [target.p.toString(), wrong[0].p.toString(), wrong[1].p.toString(), wrong[2].p.toString()],
        answer: [target.p.toString()],
        explanation: `${target.n} uses port ${target.p}. Note that the other options belong to similar protocols in the same category.`
    };
};

const TPL_OSI_DEVICES = () => {
    // NEW EXAM-LEVEL: Layer mapping with exact adjacent distractors
    const layers = [
        { layer: 'Layer 1 (Physical)', devices: ['Hub', 'Repeater', 'Cable', 'Transceiver'], wrong: ['Switch', 'Bridge', 'Router', 'Firewall'] },
        { layer: 'Layer 2 (Data Link)', devices: ['Switch', 'Bridge', 'Wireless Access Point'], wrong: ['Hub', 'Router', 'Repeater', 'Firewall'] },
        { layer: 'Layer 3 (Network)', devices: ['Router', 'Layer 3 Switch'], wrong: ['Hub', 'Switch (Layer 2)', 'Repeater', 'Bridge'] }
    ];
    const targetLayer = randItem(layers);
    const correctDevice = randItem(targetLayer.devices);
    const distractors = targetLayer.wrong.sort(() => 0.5 - Math.random()).slice(0, 3);

    return {
        domain: "1.0",
        type: "multiple-choice",
        text: `Which of the following devices operates primarily at ${targetLayer.layer} of the OSI model?`,
        options: [correctDevice, distractors[0], distractors[1], distractors[2]],
        answer: [correctDevice],
        explanation: `${correctDevice} operates at ${targetLayer.layer}.`
    };
};

const TPL_WIFI_STANDARDS = () => {
    // NEW EXAM-LEVEL: Extremely similar naming conventions
    const standards = [
        { name: '802.11a', freq: '5 GHz only', speed: '54 Mbps' },
        { name: '802.11b', freq: '2.4 GHz only', speed: '11 Mbps' },
        { name: '802.11g', freq: '2.4 GHz only', speed: '54 Mbps' },
        { name: '802.11n (Wi-Fi 4)', freq: '2.4 GHz and 5 GHz', speed: 'Up to 600 Mbps' },
        { name: '802.11ac (Wi-Fi 5)', freq: '5 GHz only', speed: 'Up to 6.9 Gbps' },
        { name: '802.11ax (Wi-Fi 6)', freq: '2.4 GHz and 5 GHz', speed: 'Up to 9.6 Gbps' }
    ];
    const target = randItem(standards);
    const wrong = standards.filter(x => x.name !== target.name).sort(() => 0.5 - Math.random()).slice(0, 3);
    
    return {
        domain: "2.0",
        type: "multiple-choice",
        text: `Which IEEE wireless standard operates at ${target.freq} and supports a maximum theoretical throughput of ${target.speed}?`,
        options: [target.name, wrong[0].name, wrong[1].name, wrong[2].name],
        answer: [target.name],
        explanation: `${target.name} operates at ${target.freq} with speeds up to ${target.speed}.`
    };
};

const TPL_IPV6_TYPES = () => {
    // NEW EXAM-LEVEL: IPv6 prefix identification
    const types = [
        { prefix: 'FE80::/10', name: 'Link-Local Unicast', wrong: ['Global Unicast', 'Unique Local Unicast', 'Multicast'] },
        { prefix: '2000::/3', name: 'Global Unicast', wrong: ['Link-Local Unicast', 'Unique Local Unicast', 'Multicast'] },
        { prefix: 'FC00::/7', name: 'Unique Local Unicast', wrong: ['Link-Local Unicast', 'Global Unicast', 'Multicast'] },
        { prefix: 'FF00::/8', name: 'Multicast', wrong: ['Link-Local Unicast', 'Unique Local Unicast', 'Global Unicast'] },
        { prefix: '::1/128', name: 'Loopback', wrong: ['Link-Local Unicast', 'Unspecified', 'Multicast'] }
    ];
    const target = randItem(types);

    return {
        domain: "1.0",
        type: "multiple-choice",
        text: `An administrator identifies an IPv6 address beginning with the prefix ${target.prefix}. What type of IPv6 address is this?`,
        options: [target.name, target.wrong[0], target.wrong[1], target.wrong[2]],
        answer: [target.name],
        explanation: `The prefix ${target.prefix} is reserved for ${target.name} addresses.`
    };
};

const TPL_SHOW_IP_ROUTE = () => {
    // NEW EXAM-LEVEL: Full routing table interpretation
    const net = rand(10, 50);
    const adOSPF = 110;
    const adEIGRP = 90;
    
    return {
        domain: "3.0",
        type: "multiple-choice",
        text: `Review the following routing table excerpt:\n\nO    10.${net}.1.0/24 [110/2] via 192.168.1.1\nD    10.${net}.1.0/25 [90/30720] via 192.168.2.1\nS    10.${net}.0.0/16 [1/0] via 192.168.3.1\nC    10.${net}.1.128/25 is directly connected\n\nIf the router receives a packet destined for 10.${net}.1.10, which next-hop IP address will it forward the packet to?`,
        options: ["192.168.2.1", "192.168.1.1", "192.168.3.1", "It will be processed locally as it is directly connected"],
        answer: ["192.168.2.1"],
        explanation: `The router uses Longest Prefix Match first. The destination 10.${net}.1.10 falls into three routes: /16, /24, and /25. The /25 route via 192.168.2.1 is the longest match, so it is chosen regardless of Administrative Distance.`
    };
};

const TPL_ROUTE_CISCO = () => {
    const dest = generateIP();
    const nextHop1 = generateIP();
    const nextHop2 = generateIP();
    const nextHop3 = generateIP();
    const ad1 = rand(90, 110);
    const ad2 = ad1 + rand(1, 10);
    const r1Type = randItem(['OSPF', 'EIGRP', 'Static']);
    const r2Type = randItem(['OSPF', 'EIGRP', 'RIP']);
    
    return {
        domain: "3.0",
        type: "multiple-choice",
        text: `A Cisco router has three routes to the destination network ${dest}/24:\n1. A ${r1Type} route via ${nextHop1} with an Administrative Distance of ${ad1}.\n2. A ${r2Type} route via ${nextHop2} with an Administrative Distance of ${ad2}.\n3. A default route (0.0.0.0/0) via ${nextHop3}.\nWhich next-hop will the router select for a packet destined to ${dest.replace(/\d+$/, '50')}?`,
        options: [nextHop1, nextHop2, nextHop3, "It will drop the packet"],
        answer: [nextHop1],
        explanation: `The router first checks for longest prefix match. Both routes 1 and 2 are /24, which is more specific than the default route. Between the two, the router prefers the lowest Administrative Distance (AD), which is ${ad1} via ${nextHop1}.`
    };
};

const TPL_ROUTE_JUNOS = () => {
    const dest = generateIP();
    const nextHop1 = generateIP();
    const nextHop2 = generateIP();
    const r1 = randItem(['Static', 'OSPF Internal', 'BGP']);
    const r2 = randItem(['Static', 'OSPF Internal', 'RIP']);
    let pref1 = r1 === 'Static' ? 5 : r1 === 'OSPF Internal' ? 10 : 170;
    let pref2 = r2 === 'Static' ? 5 : r2 === 'OSPF Internal' ? 10 : 100;
    
    if (pref1 === pref2) pref2 += 1; 
    const winner = pref1 < pref2 ? nextHop1 : nextHop2;

    return {
        domain: "3.0",
        type: "multiple-choice",
        text: `A Junos device has two routes to ${dest}/24:\n1. A ${r1} route via ${nextHop1}.\n2. A ${r2} route via ${nextHop2}.\nAssuming default route preferences, which next-hop will the device use for a packet to ${dest.replace(/\d+$/, '50')}?`,
        options: [nextHop1, nextHop2, "It will load-balance", "It will drop the packet"],
        answer: [winner],
        explanation: `Junos uses Route Preference (similar to Cisco AD). ${r1} is ${pref1}, and ${r2} is ${pref2}. Lower is preferred, so the router chooses ${winner}.`
    };
};

const TPL_MAC_TABLE = () => {
    const macSource = generateMAC();
    const macDest = generateMAC();
    const intIn = intf();
    
    return {
        domain: "2.0",
        type: "multiple-choice",
        text: `A switch receives an Ethernet frame on interface ${intIn}. The source MAC is ${macSource} and the destination MAC is ${macDest}. The switch's MAC address table is currently empty. What two actions will the switch perform? (Choose two)`,
        options: [
            `Record MAC ${macSource} out interface ${intIn}`,
            `Flood the frame out all interfaces except ${intIn}`,
            `Record MAC ${macDest} out interface ${intIn}`,
            `Drop the frame because the destination is unknown`,
            `Send an ARP request out all interfaces`
        ],
        answer: [`Record MAC ${macSource} out interface ${intIn}`, `Flood the frame out all interfaces except ${intIn}`],
        explanation: `When a switch receives a frame, it always learns the Source MAC address. If the Destination MAC is unknown, it floods the frame out all ports except the incoming port.`
    };
};

const TPL_OSPF_COST = () => {
    const refBw = randItem([100, 1000, 10000]);
    const linkBwMbps = randItem([10, 100, 1000]);
    const cost = Math.max(1, refBw / linkBwMbps);
    
    return {
        domain: "3.0",
        type: "multiple-choice",
        text: `An OSPF router has an auto-cost reference-bandwidth of ${refBw} Mbps. It has an interface with a bandwidth of ${linkBwMbps} Mbps. What will be the OSPF cost of this interface?`,
        options: [cost.toString(), (cost * 10).toString(), "1", Math.floor(cost / 2).toString()],
        answer: [cost.toString()],
        explanation: `OSPF Cost is (Reference Bandwidth / Interface Bandwidth). ${refBw} / ${linkBwMbps} = ${cost}.`
    };
};

const TPL_ATTACKS = () => {
    const attack = randItem(['ARP Spoofing', 'DHCP Starvation', 'VLAN Hopping']);
    const mitigation = attack === 'ARP Spoofing' ? 'Dynamic ARP Inspection (DAI)' :
                       attack === 'DHCP Starvation' ? 'DHCP Snooping' :
                       'Disabling DTP and using dedicated native VLANs';
                       
    return {
        domain: "4.0",
        type: "multiple-choice",
        text: `Which mechanism is specifically designed to mitigate ${attack} attacks?`,
        options: [mitigation, "IP Source Guard", "Root Guard", "BPDU Guard"],
        answer: [mitigation],
        explanation: `${mitigation} is the primary defense against ${attack}.`
    };
};

const TPL_BGP_ATTR = () => {
    const attributes = [
        { a: 'Weight', d: 'Cisco proprietary, highest is preferred, local to router' },
        { a: 'Local Preference', d: 'Sent to iBGP peers, highest is preferred, influences outbound traffic' },
        { a: 'MED', d: 'Sent to eBGP peers, lowest is preferred, influences inbound traffic' },
        { a: 'AS Path', d: 'Shortest path is preferred, prevents routing loops' }
    ];
    const target = randItem(attributes);
    const wrong = attributes.filter(x => x.a !== target.a).sort(() => 0.5 - Math.random()).slice(0, 3);
    
    return {
        domain: "3.0",
        type: "multiple-choice",
        text: `Which BGP attribute is described by the following: ${target.d}?`,
        options: [target.a, wrong[0].a, wrong[1].a, wrong[2].a],
        answer: [target.a],
        explanation: `${target.a} is exactly described as: ${target.d}.`
    };
};

const CERT_TEMPLATES = {
    ccna: [TPL_SUBNETTING, TPL_ROUTE_CISCO, TPL_MAC_TABLE, TPL_OSPF_COST, TPL_ATTACKS, TPL_IPV6_TYPES, TPL_SHOW_IP_ROUTE],
    netplus: [TPL_SUBNETTING, TPL_PORTS, TPL_ATTACKS, TPL_OSI_DEVICES, TPL_WIFI_STANDARDS, TPL_IPV6_TYPES],
    secplus: [TPL_PORTS, TPL_ATTACKS],
    encor: [TPL_ROUTE_CISCO, TPL_OSPF_COST, TPL_BGP_ATTR, TPL_SHOW_IP_ROUTE],
    jncia: [TPL_SUBNETTING, TPL_ROUTE_JUNOS, TPL_OSPF_COST, TPL_IPV6_TYPES]
};

const CERTS = {
    ccna: { file: 'cert-ccna.js', domains: ['1.0', '2.0', '3.0', '4.0', '5.0', '6.0'] },
    netplus: { file: 'cert-netplus.js', domains: ['1.0', '2.0', '3.0', '4.0', '5.0'] },
    secplus: { file: 'cert-secplus.js', domains: ['1.0', '2.0', '3.0', '4.0', '5.0'] },
    encor: { file: 'cert-encor.js', domains: ['1.0', '2.0', '3.0', '4.0', '5.0'] },
    jncia: { file: 'cert-jncia.js', domains: ['1.0', '2.0', '3.0', '4.0', '5.0'] }
};

function generateDataset(certId, numQs) {
    const config = CERTS[certId];
    const questions = [];
    let flashcards = [...FLASHCARDS[certId]];
    
    if (['ccna', 'netplus', 'encor', 'jncia'].includes(certId)) {
        for(let i=0; i < 50; i++) {
            flashcards.push(...procFlashcards());
        }
    }
    
    flashcards = flashcards.map((f, i) => ({
        id: `${certId}_fc_${1000 + i}`,
        domain: f.domain,
        front: f.front,
        back: f.back
    }));

    const templates = CERT_TEMPLATES[certId];
    const seenTexts = new Set();
    let attempts = 0;
    
    // Use an aggressive attempt limit to allow dropping impossible permutations while filling exactly as many as possible
    while (questions.length < numQs && attempts < numQs * 20) {
        attempts++;
        const template = randItem(templates);
        let q = template();
        
        // Ensure no duplicate texts exist in the generated pool itself
        if (seenTexts.has(q.text)) continue;
        seenTexts.add(q.text);

        q.id = `${certId}_q_${1000 + questions.length}`;
        q.options = shuffleArray([...new Set(q.options)]);
        
        if (!config.domains.includes(q.domain)) {
            q.domain = randItem(config.domains);
        }
        questions.push(q);
    }

    return { flashcards, questions };
}

function writeCerts() {
    const outDir = path.join(__dirname, '../js/data');
    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    Object.keys(CERTS).forEach(certId => {
        console.log(`Generating ${certId}...`);
        const data = generateDataset(certId, 500); 
        const fileContent = `/* 
 * PROCEDURALLY GENERATED CERTIFICATION DATA
 * Generated for ${certId} 
 * Contains ${data.flashcards.length} unique flashcards and ${data.questions.length} procedural practice questions.
 */

export const data = ${JSON.stringify(data, null, 4)};
`;
        fs.writeFileSync(path.join(outDir, CERTS[certId].file), fileContent);
    });
    
    console.log('Done generating all certification data.');
}

writeCerts();
